component_depth: 1
languages:
- java
exclude:
- ./ant/.*
- ./ant/ant14/.*
- ./ant/ant14/com/.*
- ./ant/ant14/com/vladium/.*
- ./ant/ant14/com/vladium/emma/.*
- ./ant/ant14/com/vladium/emma/ant/.*
- ./ant/ant14/com/vladium/emma/data/.*
- ./ant/ant14/com/vladium/emma/instr/.*
- ./ant/ant14/com/vladium/emma/report/.*
- ./ant/ant15/.*
- ./ant/ant15/com/.*
- ./ant/ant15/com/vladium/.*
- ./ant/ant15/com/vladium/emma/.*
- ./ant/ant15/com/vladium/emma/ant/.*
- ./ant/bin/.*
- ./ant/bin/com/.*
- ./ant/bin/com/vladium/.*
- ./ant/bin/com/vladium/emma/.*
- ./ant/bin/com/vladium/emma/ant/.*
- ./ant/bin/com/vladium/emma/data/.*
- ./ant/bin/com/vladium/emma/instr/.*
- ./ant/bin/com/vladium/emma/report/.*
- ./ant/data/.*
- ./ant/lib/.*
- ./ant/res/.*
- ./bin/.*
- ./bin/com/.*
- ./bin/com/vladium/.*
- ./bin/com/vladium/app/.*
- ./bin/com/vladium/emma/.*
- ./bin/com/vladium/emma/data/.*
- ./bin/com/vladium/emma/filter/.*
- ./bin/com/vladium/emma/instr/.*
- ./bin/com/vladium/emma/report/.*
- ./bin/com/vladium/emma/report/html/.*
- ./bin/com/vladium/emma/report/html/doc/.*
- ./bin/com/vladium/emma/report/txt/.*
- ./bin/com/vladium/emma/report/xml/.*
- ./bin/com/vladium/emma/rt/.*
- ./bin/com/vladium/jcd/.*
- ./bin/com/vladium/jcd/cls/.*
- ./bin/com/vladium/jcd/cls/attribute/.*
- ./bin/com/vladium/jcd/cls/constant/.*
- ./bin/com/vladium/jcd/compiler/.*
- ./bin/com/vladium/jcd/lib/.*
- ./bin/com/vladium/jcd/opcodes/.*
- ./bin/com/vladium/jcd/parser/.*
- ./bin/com/vladium/logging/.*
- ./bin/com/vladium/tools/.*
- ./bin/com/vladium/util/.*
- ./bin/com/vladium/util/args/.*
- ./bin/com/vladium/util/asserts/.*
- ./bin/com/vladium/util/exception/.*
- ./bin/com/vladium/util/exit/.*
- ./core/.*
- ./core/bin/.*
- ./core/bin/com/.*
- ./core/bin/com/vladium/.*
- ./core/bin/com/vladium/app/.*
- ./core/bin/com/vladium/emma/.*
- ./core/bin/com/vladium/emma/data/.*
- ./core/bin/com/vladium/emma/filter/.*
- ./core/bin/com/vladium/emma/instr/.*
- ./core/bin/com/vladium/emma/report/.*
- ./core/bin/com/vladium/emma/report/html/.*
- ./core/bin/com/vladium/emma/report/html/doc/.*
- ./core/bin/com/vladium/emma/report/txt/.*
- ./core/bin/com/vladium/emma/report/xml/.*
- ./core/bin/com/vladium/emma/rt/.*
- ./core/bin/com/vladium/jcd/.*
- ./core/bin/com/vladium/jcd/cls/.*
- ./core/bin/com/vladium/jcd/cls/attribute/.*
- ./core/bin/com/vladium/jcd/cls/constant/.*
- ./core/bin/com/vladium/jcd/compiler/.*
- ./core/bin/com/vladium/jcd/lib/.*
- ./core/bin/com/vladium/jcd/opcodes/.*
- ./core/bin/com/vladium/jcd/parser/.*
- ./core/bin/com/vladium/logging/.*
- ./core/bin/com/vladium/util/.*
- ./core/bin/com/vladium/util/args/.*
- ./core/bin/com/vladium/util/asserts/.*
- ./core/bin/com/vladium/util/exception/.*
- ./core/bin/com/vladium/util/exit/.*
- ./core/data/.*
- ./core/data/com/.*
- ./core/data/com/vladium/.*
- ./core/data/com/vladium/app/.*
- ./core/java12/.*
- ./core/java12/com/.*
- ./core/java12/com/vladium/.*
- ./core/java12/com/vladium/emma/.*
- ./core/java12/com/vladium/emma/data/.*
- ./core/java12/com/vladium/emma/filter/.*
- ./core/java12/com/vladium/emma/instr/.*
- ./core/java12/com/vladium/emma/report/.*
- ./core/java12/com/vladium/emma/report/html/.*
- ./core/java12/com/vladium/emma/report/html/doc/.*
- ./core/java12/com/vladium/emma/report/txt/.*
- ./core/java12/com/vladium/emma/report/xml/.*
- ./core/java12/com/vladium/emma/rt/.*
- ./core/java12/com/vladium/jcd/.*
- ./core/java12/com/vladium/jcd/cls/.*
- ./core/java12/com/vladium/jcd/cls/attribute/.*
- ./core/java12/com/vladium/jcd/cls/constant/.*
- ./core/java12/com/vladium/jcd/compiler/.*
- ./core/java12/com/vladium/jcd/lib/.*
- ./core/java12/com/vladium/jcd/opcodes/.*
- ./core/java12/com/vladium/jcd/parser/.*
- ./core/java12/com/vladium/logging/.*
- ./core/java12/com/vladium/util/.*
- ./core/java12/com/vladium/util/args/.*
- ./core/java12/com/vladium/util/asserts/.*
- ./core/java12/com/vladium/util/exception/.*
- ./core/java13/.*
- ./core/java13/com/.*
- ./core/java13/com/vladium/.*
- ./core/java13/com/vladium/util/.*
- ./core/java13/com/vladium/util/exit/.*
- ./core/java14/.*
- ./core/java14/com/.*
- ./core/java14/com/vladium/.*
- ./core/java14/com/vladium/util/.*
- ./core/lib/.*
- ./core/res/.*
- ./core/res/com/.*
- ./core/res/com/vladium/.*
- ./core/res/com/vladium/emma/.*
- ./core/res/com/vladium/emma/data/.*
- ./core/res/com/vladium/emma/instr/.*
- ./core/res/com/vladium/emma/report/.*
- ./lib/.*
- ./lib/external/.*
- ./lib/internal/.*
- ./tools/.*
- ./tools/java/.*
- ./tools/java/com/.*
- ./tools/java/com/vladium/.*
- ./tools/java/com/vladium/tools/.*
